# Changes here will be overwritten by Copier.
_commit: 1.8.4
_src_path: gh:pawamoy/copier-uv
author_email: dev@pawamoy.fr
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2023'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: dev@pawamoy.fr
copyright_license: ISC
insiders: true
insiders_email: insiders@pawamoy.fr
insiders_repository_name: insiders-project
project_description: Manage your Insiders projects.
project_name: insiders
public_release: true
python_package_command_line_name: insiders
python_package_distribution_name: insiders
python_package_import_name: insiders
repository_name: insiders-project
repository_namespace: pawamoy
repository_provider: github.com

